server:
  port: 8005
spring:
  config:
    import: optional:file:.env[.properties]
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8000}
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8000/.well-known/jwks.json}
  # Datasource configuration
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./database/resources
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
# Application custom properties
we:
  elearning:
    security:
      cors:
        origins: ${CORS_ORIGINS:http://localhost:3000}
    workspace-manager:
      base-url: ${WORKSPACE_MANAGER_BASE_URL:http://localhost:8000}