server:
  port: 8005
# spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8000
spring:
  config:
    import: optional:file:.env[.properties]
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:-}
          jwk-set-uri: ${JWK_SET_URI:-}
          audiences:
            - ${AUTH0_AUDIENCE:-}
  # Datasource configuration
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./database/resources
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
# Application custom properties
# we.elearning.security.auth0.user-info-url: https://we-elearning.us.auth0.com/userinfo
we:
  elearning:
    security:
      cors:
        origins: ${CORS_ORIGINS:http://localhost:3000}
      auth0:
        audience: ${AUTH0_AUDIENCE:https://api.we-elearning.com/api/v1/}
        user-info-url: ${AUTH0_USER_INFO_URL:https://we-elearning.us.auth0.com/userinfo}
        client-id: ${AUTH0_CLIENT_ID:-}
        client-secret: ${AUTH0_CLIENT_SECRET:-}
    workspace-manager:
      base-url: ${WORKSPACE_MANAGER_BASE_URL:http://localhost:8000}