/* eslint-disable @typescript-eslint/no-misused-promises */
import React from "react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";
import type { Playground } from "../server/lib/axios";
import Button from "../components/Button";

const Home: NextPage = () => {
  // states
  const [loading, setLoading] = React.useState(false);
  // hooks
  const { mutateAsync } = api.spaces.create.useMutation();
  // handlers and callbacks
  const handleSpaceCreating = React.useCallback(async () => {
    setLoading(true);
    const result = (await mutateAsync()) as Playground;
    setLoading(false);
    window.open(result.instanceUrl, "_blank");
  }, [mutateAsync]);
  return (
    <>
      <Head>
        <title>coder cm</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Coder<span className="text-[hsl(280,100%,70%)]">CM</span>
          </h1>
          <p className="text-2xl text-white">
            <Button
              loading={loading}
              onClick={handleSpaceCreating}
              className="bg-teal-700 px-3 py-2 text-sm uppercase text-white hover:bg-teal-600"
            >
              create space
            </Button>
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
